### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by caingaroo** [luca28pet/SimpleHungerGames#1]
This is the error that comes up on my server
[Server] 21:50:32 [INFO] Loading source plugin SimpleHungerGames v1.2
[Server] 
[Server] Parse error: syntax error, unexpected '}' in /storage/emulated/0/Pocketmine/plugins/SimpleHungerGames-master/src/SimpleHungerGames/Main.php on line 102
[Server] 21:50:32 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 21:50:32 [EMERGENCY] Please submit the "/storage/emulated/0/Pocketmine/CrashDump_Fri_Feb_27-21.50.32-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 21:50:32 [INFO] Disabling DevTools v1.10.0

**Comment by luca28pet** [comment]
This plugin is NOT ready.
If a plugin is not in the public PocketMine repo that means it is in development and not working.

**Comment by luca28pet** [comment]
This plugin is NOT ready.
If a plugin is not in the public PocketMine repo that means it is in development and not working.
